# Config for feature generation 


league:
  players_rules:
    # this feature used while we parse teams games insted players games
    # this is how many good players should be in current match
    # for example in current match we have 1 good player and 4 bad, so drop it
    min_good_players_in_stack: 4
    # this is how many similar players to current match should be in past (window) matches
    # for example in previous match team played with 3 standoff, so only 2 players from current match and previous match is match
    min_match_players_in_window: 4
    # minimum games played by player in train dataset
    # otherwise this player will not tokinized
    min_played_games: 32

  teams_rules:
    # minimum games that team should play
    # otherwise this team will not tokinized
    min_played_games: 32

  # Maximum num of games in one window, otherwise restrict it
  window_size: 32
  # Min num of games in one window, otherwise drop it
  window_min_size: 8
  # padding mode, pad at the start or end
  window_pad_mode: start
  # Features used in prediction
  features:
    # linear - put as numbers
    # categorical - put in embedding, quantize if necessary

    # Features includes in window
    window:
      stats: linear
      opponent_stats: linear
      opponent: False # Include opponent's embeding in each past game in window
      result: categorical

    # Features includes in last linear layers
    tabular: 
      grid: False
      teams: True
      players: False
      games_num: False
      prize_pool: True



public:
  players_rules:
    # this is how many good players should be in current match
    # for example in current match we have 1 good player and 4 bad, so drop it
    min_good_players_in_stack: 0
    # minimum games played by player in train dataset
    # otherwise this player will not tokinized
    min_played_games: 64