# This settings aply to drop matches

public:
  # min is >=
  # max is <=
  min: 
    duration: 900
  max: 
    duration: 5000

  # in mounth
  # matches older than this will be droped 
  match_age: 24
  
  # This is for team summary
  rd: # summary `r_` + `d_` stats
    min: 
      tower_damage: 100
      kills: 10
    max: null

  # This is also for team summary
  r_d: # `r_` or `d_` stats
    min: 
      kills: 2
    max: null


league:
  tiers:
    # premium is official valve tournaments
    premium: 
      include: True
      prize_pool: 50_000
    # unofficial tournaments
    professional: 
      include: True
      prize_pool: 50_000
    # smth like trash
    excluded:
      include: True
      prize_pool: 75_000
    # just in case
    others:
      include: True
      prize_pool: 75_000
